[relay]
mode = "direct"

[network]
google_ip = "216.239.38.120"
front_domain = "www.google.com"
listen_host = "127.0.0.1"
listen_port = 8085
socks5_port = 8086
verify_ssl = true

[network.hosts]

[scan]

[logging]
log_level = "info"

[exit_node]
enabled = false
